### ISSUE TITLE
Cannot scroll the list of options

### ISSUE THREAD

**Issue by cephirothdy2j** [bvaughn/react-virtualized-select#75]
Scrolling using the mouse / track pad is creating a weird rubber-band effect, where the list never goes far without snapping back to the top of the list of options. Note that the component behaves expectedly when using the arrow keys to navigate up and down the list of options.

![virtualized-scrolling-issues](https://user-images.githubusercontent.com/881769/30624677-d058267a-9d8c-11e7-8cf3-a4502faf36f9.gif)

Easiest way to reproduce ...

1. Create a new React app with [create-react-app](https://github.com/facebookincubator/create-react-app)
2. Enter the new directory and install this module with `npm install react-virtualized-select`
3. Overwrite `src/App.js` with this code, which is copied from your [simple example](https://github.com/bvaughn/react-virtualized-select/blob/master/README.md#simple-example) and modified to create more options and to export properly.
```
import React, { Component } from 'react'
import VirtualizedSelect from 'react-virtualized-select'

import 'react-select/dist/react-select.css'
import 'react-virtualized/styles.css'
import 'react-virtualized-select/styles.css'

const options = [];
for (let i = 0; i < 2000; i++) {
  options.push({label: String(i), value: i});
}

class App extends Component {
  constructor (props) {
    super(props)

    this.state = {}
  }
  render () {
    return (
      <VirtualizedSelect
        options={options}
        onChange={(selectValue) => this.setState({ selectValue })}
        value={this.state.selectValue}
      />
    )
  }
}
export default App;
```
4. Start the project with `npm start`.

**Comment by seanpavlov** [comment]
I missed your issue when I created mine, but it's basically the same issue.
My solution was to use version 9.0.0 of react-virtualized instead of 9.10.1 and also copied VirtualizedSelect.js from this repo into my project. Does that work for you as well?

**Comment by bvaughn** [comment]
@seanpavlov You downgraded from 9.10 to 9.0? I'm curious if you tried 9.9.

At a glance this issue looks related to a 9.10 regression, bvaughn/react-virtualized/issues/816

**Comment by austin94** [comment]
@bvaughn I was able to locally build the documentation on `v9.9.0 c828cf2ab0cf35ff2cc7462af02c5269e352df1c` and the ArrowKeyStepper demo page is scrolling correctly.

**Comment by bvaughn** [comment]
Thanks for confirming this was a regression in 9.10.

My guess is bvaughn/react-virtualized/pull/798

**Comment by cephirothdy2j** [comment]
I too can confirm that downgrading to `react-virtualized@9.9.0` solves the issue. Thanks for pointing us in the right direction.

I'll look at that PR and see if I can get to the bottom of the issue. If I'm successful, would you be putting out a patch release quickly?

**Comment by bvaughn** [comment]
Yeah

**Comment by sdemjanenko** [comment]
If you are using yarn v1 you can add this to your package.json:

```
"resolutions": {
    "react-virtualized-select/react-virtualized": "9.9.0"
  }
```
And that will lock the sub-dependency to a version that works with react-virtualized-select.

**Comment by martinmenneske** [comment]
I can't get this to work even with downgrading to 9.9.0. Do I need to install a specific version of react-virtualized-select as well? I tried downgrading it to 3.0.1, but no luck.

**Comment by istarkov** [comment]
@bvaughn It was introduced somewhere inbetween 14 -23 july
All react-virtualized builds after 23 July has this bug.

**Comment by bvaughn** [comment]
This has been fixed by react-virtualized 9.11.0 release that I am publishing presently. Sorry for the inconvenience!

**Comment by istarkov** [comment]
Seems like not fully fixed, become better - now there are no rendering issues, but scroll still jumping. I'll investigate it later.

**Comment by lothisoft** [comment]
Shouldn't this issue be re-opened?

**Comment by bvaughn** [comment]
Nope. The issue originally reported was a transient bug in a specific release of react-virtualized that was fixed by the subsequent release. I'm not sure what the "scroll jumping" comment refers to, but it's not the original issue.

So far as I see on [the demo page](https://bvaughn.github.io/react-virtualized-select/), scrolling works fine.

**Comment by istarkov** [comment]
Seems like the problem that fix here https://github.com/bvaughn/react-virtualized/pull/825/files
had not fixed all the occurrence of same check as before `typeof prevProps.rowHeight === "number" ? prevProps.rowHeight : null,`
And in all other situations if you have a rowHeight as a function 
like here https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L834 and in other places we have a problem.

**Comment by istarkov** [comment]
So I think it is the same issue as current.

**Comment by bvaughn** [comment]
Those 2 places you linked point to different helper methods, so the fact that the code being passed in look similar doesn't necessary indicate that there's any problem.

Regardless, the broken behavior reported against _this_ project originally in this issue is no longer occurring. So far as I see, no broken behavior is occurring.

If I'm wrong though, please open a new issue with repro steps. 😄

**Comment by istarkov** [comment]
For anyone who has the same problem with releases after 9.9.0 and have more time, occasional jumps ocured at this line https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/Grid.js#L1364 sometimes (very rare) for unknown reasons `_getCalculatedScrollTop` returns small values at scrolling.

**Comment by vanessa** [comment]
The same thing is happening to me. I'm using a VirtualizedSelect with custom option renderer.

![rvs](https://user-images.githubusercontent.com/23136832/42838299-d217e8a6-89d6-11e8-89cd-271c69eaedb1.gif)

**Comment by bvaughn** [comment]
@vanessa At a glance, this looks like you might be forgetting to use the `style` param

**Comment by bvaughn** [comment]
In your current code above, it doesn't look like you're using [the `style` param passed to the custom option renderer](https://github.com/bvaughn/react-virtualized-select#custom-option-renderer). You're using your own style, which is masking the warning, but that style isn't the one passed to you– so it doesn't have the positioning info.

**Comment by lothisoft** [comment]
@bvaughn is right.  Move your custom style to a css file with a proper className and give the div the same className.  

Then add
`style={style}`
to your div.

**Comment by bvaughn** [comment]
Or you could spread:
```js
<div
  style={{
    ...style,
    display: 'flex',
    alignItems: 'center',
    height: 100,
    justifyContent: 'space-between'
  }}
  key={option.value}
  role="presentation"
  onClick={() => selectValue(option)}
  onMouseEnter={() => focusOption(option)}
>
```
